### ISSUE TITLE
M1 one support

### ISSUE THREAD

**Issue by ghost** [lokalise/homebrew-cli-2#2]
Hi people,

Any plans for the Apple Silicon support?

Kind Regards,
Eugen

**Comment by carstenhag** [comment]
@lokalise-engineering @andrewLab-lokalise @nickustinov I would guess that lokalise does support M1 processors, or is that not the case? If yes, please close this ticket :)

**Comment by andrewLab-lokalise** [comment]
@carstenhag, thank you for mentioning. @ghost, @fujikky, M1 support was added in v2.6.7 (release of 27 Jul 2021)

**Comment by carstenhag** [comment]
Great, thanks.
